# Data Profiling

In [1]:
import pandas as pd
df = pd.read_csv("/content/canada_gas_prices.csv")
df

,date,city,province,fuel,service,octane,cents_per_litre
0,1979-01,St. John's,Newfoundland and Labrador,gasoline,full,regular,26.0
1,1979-01,Charlottetown,Prince Edward Island,gasoline,full,regular,24.6
2,1979-01,Halifax,Nova Scotia,gasoline,full,regular,23.4
3,1979-01,Saint John,New Brunswick,gasoline,full,regular,23.2
4,1979-01,Québec City,Quebec,gasoline,full,regular,22.6
...,...,...,...,...,...,...,...
42972,2023-01,Whitehorse,Yukon,household heating,NaN,NaN,204.8
42973,2023-01,Yellowknife,Northwest Territories,gasoline,self,regular,158.0
42974,2023-01,Yellowknife,Northwest Territories,gasoline,self,premium,173.5
42975,2023-01,Yellowknife,Northwest Territories,diesel,self,NaN,197.1
42976,2023-01,Yellowknife,Northwest Territories,household heating,NaN,NaN,175.1

Check for the first and last 25 rows

In [ ]:
df.head(25)

,date,city,province,fuel,service,octane,cents_per_litre
0,1979-01,St. John's,Newfoundland and Labrador,gasoline,full,regular,26.0
1,1979-01,Charlottetown,Prince Edward Island,gasoline,full,regular,24.6
2,1979-01,Halifax,Nova Scotia,gasoline,full,regular,23.4
3,1979-01,Saint John,New Brunswick,gasoline,full,regular,23.2
4,1979-01,Québec City,Quebec,gasoline,full,regular,22.6
5,1979-01,Montréal,Quebec,gasoline,full,regular,22.6
6,1979-01,Ottawa,Ontario,gasoline,full,regular,22.8
7,1979-01,Toronto,Ontario,gasoline,full,regular,23.0
8,1979-01,Thunder Bay,Ontario,gasoline,full,regular,22.7
9,1979-01,Winnipeg,Manitoba,gasoline,full,regular,22.0
10,1979-01,Regina,Saskatchewan,gasoline,full,regular,22.8
11,1979-01,Saskatoon,Saskatchewan,gasoline,full,regular,22.7
12,1979-01,Edmonton,Alberta,gasoline,full,regular,18.3
13,1979-01,Calgary,Alberta,gasoline,full,regular,18.7
14,1979-01,Vancouver,British Columbia,gasoline,full,regular,21.8
15,1979-02,St. John's,Newfoundland and Labrador,gasoline,full,regular,26.2
16,1979-02,Charlottetown,Prince Edward Island,gasoline,full,regular,24.8
17,1979-02,Halifax,Nova Scotia,gasoline,full,regular,23.6
18,1979-02,Saint John,New Brunswick,gasoline,full,regular,23.6
19,1979-02,Québec City,Quebec,gasoline,full,regular,22.7
20,1979-02,Montréal,Quebec,gasoline,full,regular,22.6
21,1979-02,Ottawa,Ontario,gasoline,full,regular,22.8
22,1979-02,Toronto,Ontario,gasoline,full,regular,23.2
23,1979-02,Thunder Bay,Ontario,gasoline,full,regular,22.7
24,1979-02,Winnipeg,Manitoba,gasoline,full,regular,20.9

In [ ]:
df.tail(25)

,date,city,province,fuel,service,octane,cents_per_litre
42952,2023-01,Saskatoon,Saskatchewan,gasoline,self,premium,169.4
42953,2023-01,Saskatoon,Saskatchewan,diesel,self,NaN,191.7
42954,2023-01,Saskatoon,Saskatchewan,household heating,NaN,NaN,171.4
42955,2023-01,Edmonton,Alberta,gasoline,self,regular,127.4
42956,2023-01,Edmonton,Alberta,gasoline,self,premium,149.8
42957,2023-01,Edmonton,Alberta,diesel,self,NaN,170.9
42958,2023-01,Calgary,Alberta,gasoline,self,regular,128.6
42959,2023-01,Calgary,Alberta,gasoline,self,premium,151.6
42960,2023-01,Calgary,Alberta,diesel,self,NaN,169.0
42961,2023-01,Vancouver,British Columbia,gasoline,self,regular,179.3
42962,2023-01,Vancouver,British Columbia,gasoline,self,premium,203.4
42963,2023-01,Vancouver,British Columbia,diesel,self,NaN,197.8
42964,2023-01,Vancouver,British Columbia,household heating,NaN,NaN,181.8
42965,2023-01,Victoria,British Columbia,gasoline,self,regular,173.4
42966,2023-01,Victoria,British Columbia,gasoline,self,premium,195.2
42967,2023-01,Victoria,British Columbia,diesel,self,NaN,192.2
42968,2023-01,Victoria,British Columbia,household heating,NaN,NaN,206.0
42969,2023-01,Whitehorse,Yukon,gasoline,self,regular,169.6
42970,2023-01,Whitehorse,Yukon,gasoline,self,premium,180.1
42971,2023-01,Whitehorse,Yukon,diesel,self,NaN,209.6
42972,2023-01,Whitehorse,Yukon,household heating,NaN,NaN,204.8
42973,2023-01,Yellowknife,Northwest Territories,gasoline,self,regular,158.0
42974,2023-01,Yellowknife,Northwest Territories,gasoline,self,premium,173.5
42975,2023-01,Yellowknife,Northwest Territories,diesel,self,NaN,197.1
42976,2023-01,Yellowknife,Northwest Territories,household heating,NaN,NaN,175.1

Check for information about the data set

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42977 entries, 0 to 42976
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             42977 non-null  object
 1   city             42977 non-null  object
 2   province         42977 non-null  object
 3   fuel             42977 non-null  object
 4   service          36625 non-null  object
 5   octane           26224 non-null  object
 6   cents_per_litre  42977 non-null  float64
dtypes: float64(1), object(6)
memory usage: 2.3+ MB

Rename household heating to natural gas

In [ ]:
df.isnull().any()

date               False
city               False
province           False
fuel               False
service             True
octane              True
cents_per_litre    False
dtype: bool

Rename household heating to natural gas

In [2]:
df["fuel"] = df["fuel"].replace("household heating", "natural gas")
df.tail(25)

,date,city,province,fuel,service,octane,cents_per_litre
42952,2023-01,Saskatoon,Saskatchewan,gasoline,self,premium,169.4
42953,2023-01,Saskatoon,Saskatchewan,diesel,self,NaN,191.7
42954,2023-01,Saskatoon,Saskatchewan,natural gas,NaN,NaN,171.4
42955,2023-01,Edmonton,Alberta,gasoline,self,regular,127.4
42956,2023-01,Edmonton,Alberta,gasoline,self,premium,149.8
42957,2023-01,Edmonton,Alberta,diesel,self,NaN,170.9
42958,2023-01,Calgary,Alberta,gasoline,self,regular,128.6
42959,2023-01,Calgary,Alberta,gasoline,self,premium,151.6
42960,2023-01,Calgary,Alberta,diesel,self,NaN,169.0
42961,2023-01,Vancouver,British Columbia,gasoline,self,regular,179.3
42962,2023-01,Vancouver,British Columbia,gasoline,self,premium,203.4
42963,2023-01,Vancouver,British Columbia,diesel,self,NaN,197.8
42964,2023-01,Vancouver,British Columbia,natural gas,NaN,NaN,181.8
42965,2023-01,Victoria,British Columbia,gasoline,self,regular,173.4
42966,2023-01,Victoria,British Columbia,gasoline,self,premium,195.2
42967,2023-01,Victoria,British Columbia,diesel,self,NaN,192.2
42968,2023-01,Victoria,British Columbia,natural gas,NaN,NaN,206.0
42969,2023-01,Whitehorse,Yukon,gasoline,self,regular,169.6
42970,2023-01,Whitehorse,Yukon,gasoline,self,premium,180.1
42971,2023-01,Whitehorse,Yukon,diesel,self,NaN,209.6
42972,2023-01,Whitehorse,Yukon,natural gas,NaN,NaN,204.8
42973,2023-01,Yellowknife,Northwest Territories,gasoline,self,regular,158.0
42974,2023-01,Yellowknife,Northwest Territories,gasoline,self,premium,173.5
42975,2023-01,Yellowknife,Northwest Territories,diesel,self,NaN,197.1
42976,2023-01,Yellowknife,Northwest Territories,natural gas,NaN,NaN,175.1

Fill the missing values for service and octance with no type

In [3]:
df['service'] = df['service'].fillna('no type')
df.tail(25)

,date,city,province,fuel,service,octane,cents_per_litre
42952,2023-01,Saskatoon,Saskatchewan,gasoline,self,premium,169.4
42953,2023-01,Saskatoon,Saskatchewan,diesel,self,NaN,191.7
42954,2023-01,Saskatoon,Saskatchewan,natural gas,no type,NaN,171.4
42955,2023-01,Edmonton,Alberta,gasoline,self,regular,127.4
42956,2023-01,Edmonton,Alberta,gasoline,self,premium,149.8
42957,2023-01,Edmonton,Alberta,diesel,self,NaN,170.9
42958,2023-01,Calgary,Alberta,gasoline,self,regular,128.6
42959,2023-01,Calgary,Alberta,gasoline,self,premium,151.6
42960,2023-01,Calgary,Alberta,diesel,self,NaN,169.0
42961,2023-01,Vancouver,British Columbia,gasoline,self,regular,179.3
42962,2023-01,Vancouver,British Columbia,gasoline,self,premium,203.4
42963,2023-01,Vancouver,British Columbia,diesel,self,NaN,197.8
42964,2023-01,Vancouver,British Columbia,natural gas,no type,NaN,181.8
42965,2023-01,Victoria,British Columbia,gasoline,self,regular,173.4
42966,2023-01,Victoria,British Columbia,gasoline,self,premium,195.2
42967,2023-01,Victoria,British Columbia,diesel,self,NaN,192.2
42968,2023-01,Victoria,British Columbia,natural gas,no type,NaN,206.0
42969,2023-01,Whitehorse,Yukon,gasoline,self,regular,169.6
42970,2023-01,Whitehorse,Yukon,gasoline,self,premium,180.1
42971,2023-01,Whitehorse,Yukon,diesel,self,NaN,209.6
42972,2023-01,Whitehorse,Yukon,natural gas,no type,NaN,204.8
42973,2023-01,Yellowknife,Northwest Territories,gasoline,self,regular,158.0
42974,2023-01,Yellowknife,Northwest Territories,gasoline,self,premium,173.5
42975,2023-01,Yellowknife,Northwest Territories,diesel,self,NaN,197.1
42976,2023-01,Yellowknife,Northwest Territories,natural gas,no type,NaN,175.1

In [4]:
df['octane'] = df['octane'].fillna('no type')
df.tail(25)

,date,city,province,fuel,service,octane,cents_per_litre
42952,2023-01,Saskatoon,Saskatchewan,gasoline,self,premium,169.4
42953,2023-01,Saskatoon,Saskatchewan,diesel,self,no type,191.7
42954,2023-01,Saskatoon,Saskatchewan,natural gas,no type,no type,171.4
42955,2023-01,Edmonton,Alberta,gasoline,self,regular,127.4
42956,2023-01,Edmonton,Alberta,gasoline,self,premium,149.8
42957,2023-01,Edmonton,Alberta,diesel,self,no type,170.9
42958,2023-01,Calgary,Alberta,gasoline,self,regular,128.6
42959,2023-01,Calgary,Alberta,gasoline,self,premium,151.6
42960,2023-01,Calgary,Alberta,diesel,self,no type,169.0
42961,2023-01,Vancouver,British Columbia,gasoline,self,regular,179.3
42962,2023-01,Vancouver,British Columbia,gasoline,self,premium,203.4
42963,2023-01,Vancouver,British Columbia,diesel,self,no type,197.8
42964,2023-01,Vancouver,British Columbia,natural gas,no type,no type,181.8
42965,2023-01,Victoria,British Columbia,gasoline,self,regular,173.4
42966,2023-01,Victoria,British Columbia,gasoline,self,premium,195.2
42967,2023-01,Victoria,British Columbia,diesel,self,no type,192.2
42968,2023-01,Victoria,British Columbia,natural gas,no type,no type,206.0
42969,2023-01,Whitehorse,Yukon,gasoline,self,regular,169.6
42970,2023-01,Whitehorse,Yukon,gasoline,self,premium,180.1
42971,2023-01,Whitehorse,Yukon,diesel,self,no type,209.6
42972,2023-01,Whitehorse,Yukon,natural gas,no type,no type,204.8
42973,2023-01,Yellowknife,Northwest Territories,gasoline,self,regular,158.0
42974,2023-01,Yellowknife,Northwest Territories,gasoline,self,premium,173.5
42975,2023-01,Yellowknife,Northwest Territories,diesel,self,no type,197.1
42976,2023-01,Yellowknife,Northwest Territories,natural gas,no type,no type,175.1

Check unique values of cities and fuel type

In [5]:
df.city.value_counts()

city
Charlottetown    2551
Montréal         2551
Winnipeg         2551
Québec City      2551
Toronto          2551
Ottawa           2551
Vancouver        2551
Regina           2551
Victoria         2527
Whitehorse       2419
Yellowknife      2399
Saskatoon        2334
St. John's       2275
Halifax          2223
Saint John       2207
Calgary          2154
Edmonton         2154
Thunder Bay      1877
Name: count, dtype: int64

In [ ]:
df.fuel.value_counts()

fuel
gasoline             26224
diesel               10401
household heating     6352
Name: count, dtype: int64

# Data Wrangling

Filter data according to trageted years, service and fuel type

In [6]:
df_filtered = df[(df['date'] >= '2000-01') & (df['date'] <= '2023-01') & (df['service'].isin(['self', 'no type'])) & (df['fuel'].isin(['gasoline', 'natural gas']))]
df_filtered.head(25)

,date,city,province,fuel,service,octane,cents_per_litre
16169,2000-01,St. John's,Newfoundland and Labrador,gasoline,self,regular,74.9
16171,2000-01,St. John's,Newfoundland and Labrador,gasoline,self,premium,81.3
16173,2000-01,St. John's,Newfoundland and Labrador,natural gas,no type,no type,49.3
16175,2000-01,Charlottetown,Prince Edward Island,gasoline,self,regular,63.3
16177,2000-01,Charlottetown,Prince Edward Island,gasoline,self,premium,67.4
16180,2000-01,Charlottetown,Prince Edward Island,natural gas,no type,no type,42.3
16182,2000-01,Halifax,Nova Scotia,gasoline,self,regular,69.6
16184,2000-01,Halifax,Nova Scotia,gasoline,self,premium,74.9
16186,2000-01,Halifax,Nova Scotia,natural gas,no type,no type,49.0
16188,2000-01,Saint John,New Brunswick,gasoline,self,regular,63.8
16190,2000-01,Saint John,New Brunswick,gasoline,self,premium,70.6
16192,2000-01,Saint John,New Brunswick,natural gas,no type,no type,49.9
16194,2000-01,Québec City,Quebec,gasoline,self,regular,64.0
16196,2000-01,Québec City,Quebec,gasoline,self,premium,71.2
16199,2000-01,Québec City,Quebec,natural gas,no type,no type,43.0
16201,2000-01,Montréal,Quebec,gasoline,self,regular,68.8
16203,2000-01,Montréal,Quebec,gasoline,self,premium,76.1
16206,2000-01,Montréal,Quebec,natural gas,no type,no type,43.0
16208,2000-01,Ottawa,Ontario,gasoline,self,regular,62.7
16210,2000-01,Ottawa,Ontario,gasoline,self,premium,72.9
16213,2000-01,Ottawa,Ontario,natural gas,no type,no type,47.7
16215,2000-01,Toronto,Ontario,gasoline,self,regular,63.5
16217,2000-01,Toronto,Ontario,gasoline,self,premium,73.3
16220,2000-01,Toronto,Ontario,natural gas,no type,no type,48.0
16222,2000-01,Thunder Bay,Ontario,gasoline,self,regular,65.1

In [ ]:
df_filtered.city.value_counts()

city
St. John's       831
Charlottetown    831
Halifax          831
Saint John       831
Québec City      831
Montréal         831
Ottawa           831
Toronto          831
Thunder Bay      831
Winnipeg         831
Regina           831
Saskatoon        831
Victoria         831
Vancouver        831
Whitehorse       831
Yellowknife      831
Calgary          554
Edmonton         554
Name: count, dtype: int64

In [ ]:
df_filtered.fuel.value_counts()

fuel
gasoline       8864
natural gas    4432
Name: count, dtype: int64

In [ ]:
df_filtered.describe(include = 'all')

,date,city,province,fuel,service,octane,cents_per_litre,fuel_type
count,13296,13296,13296,13296,13296,13296,13296.000000,13296
unique,277,16,11,2,2,3,NaN,3
top,2023-01,St. John's,Ontario,gasoline,self,regular,NaN,gasoline_regular
freq,48,831,2493,8864,8864,4432,NaN,4432
mean,NaN,NaN,NaN,NaN,NaN,NaN,109.815305,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,31.450500,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,37.300000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,87.700000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,109.700000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,128.700000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,275.500000,NaN

Filter out cities with no data on natural gas

In [7]:
df_filtered = df_filtered[~df_filtered['city'].isin(['Calgary', 'Edmonton'])]
df_filtered.head()

,date,city,province,fuel,service,octane,cents_per_litre
16169,2000-01,St. John's,Newfoundland and Labrador,gasoline,self,regular,74.9
16171,2000-01,St. John's,Newfoundland and Labrador,gasoline,self,premium,81.3
16173,2000-01,St. John's,Newfoundland and Labrador,natural gas,no type,no type,49.3
16175,2000-01,Charlottetown,Prince Edward Island,gasoline,self,regular,63.3
16177,2000-01,Charlottetown,Prince Edward Island,gasoline,self,premium,67.4

Feature engineer the fuel type column by combining the fuel and octane columns

In [8]:
df_filtered = df_filtered.copy()
df_filtered['fuel_type'] = df_filtered['fuel'] + "_" + df_filtered['octane']
df_filtered.head()

,date,city,province,fuel,service,octane,cents_per_litre,fuel_type
16169,2000-01,St. John's,Newfoundland and Labrador,gasoline,self,regular,74.9,gasoline_regular
16171,2000-01,St. John's,Newfoundland and Labrador,gasoline,self,premium,81.3,gasoline_premium
16173,2000-01,St. John's,Newfoundland and Labrador,natural gas,no type,no type,49.3,natural gas_no type
16175,2000-01,Charlottetown,Prince Edward Island,gasoline,self,regular,63.3,gasoline_regular
16177,2000-01,Charlottetown,Prince Edward Island,gasoline,self,premium,67.4,gasoline_premium

Now check for any null values

In [ ]:
df_filtered.isnull().any()

date               False
city               False
province           False
fuel               False
service            False
octane             False
cents_per_litre    False
fuel_type          False
dtype: bool

Group fuel types in different columns based on cents per litre and octane type

In [9]:
df_pivot = df_filtered.pivot_table(
    index=['date', 'city', 'province'],
    columns='fuel_type',
    values='cents_per_litre'
).reset_index()
df_pivot.columns.name = None
df_pivot.head(25)

,date,city,province,gasoline_premium,gasoline_regular,natural gas_no type
0,2000-01,Charlottetown,Prince Edward Island,67.4,63.3,42.3
1,2000-01,Halifax,Nova Scotia,74.9,69.6,49.0
2,2000-01,Montréal,Quebec,76.1,68.8,43.0
3,2000-01,Ottawa,Ontario,72.9,62.7,47.7
4,2000-01,Québec City,Quebec,71.2,64.0,43.0
5,2000-01,Regina,Saskatchewan,74.8,65.2,49.4
6,2000-01,Saint John,New Brunswick,70.6,63.8,49.9
7,2000-01,Saskatoon,Saskatchewan,74.0,64.5,50.5
8,2000-01,St. John's,Newfoundland and Labrador,81.3,74.9,49.3
9,2000-01,Thunder Bay,Ontario,74.8,65.1,48.0
10,2000-01,Toronto,Ontario,73.3,63.5,48.0
11,2000-01,Vancouver,British Columbia,70.3,60.2,50.4
12,2000-01,Victoria,British Columbia,74.9,64.6,49.1
13,2000-01,Whitehorse,Yukon,79.4,73.8,47.4
14,2000-01,Winnipeg,Manitoba,71.1,61.9,50.5
15,2000-01,Yellowknife,Northwest Territories,84.8,77.9,47.7
16,2000-02,Charlottetown,Prince Edward Island,67.5,63.3,42.3
17,2000-02,Halifax,Nova Scotia,76.7,70.8,60.5
18,2000-02,Montréal,Quebec,80.6,73.8,59.1
19,2000-02,Ottawa,Ontario,74.8,64.7,55.9
20,2000-02,Québec City,Quebec,76.5,69.4,57.9
21,2000-02,Regina,Saskatchewan,75.9,66.3,49.9
22,2000-02,Saint John,New Brunswick,75.4,68.6,63.0
23,2000-02,Saskatoon,Saskatchewan,76.4,66.9,50.8
24,2000-02,St. John's,Newfoundland and Labrador,83.1,76.5,58.0

Rename the pivoted column name

In [10]:
df_pivot.rename(columns={"natural gas_no type": "natural gas"}, inplace=True)
df_pivot.head(25)

,date,city,province,gasoline_premium,gasoline_regular,natural gas
0,2000-01,Charlottetown,Prince Edward Island,67.4,63.3,42.3
1,2000-01,Halifax,Nova Scotia,74.9,69.6,49.0
2,2000-01,Montréal,Quebec,76.1,68.8,43.0
3,2000-01,Ottawa,Ontario,72.9,62.7,47.7
4,2000-01,Québec City,Quebec,71.2,64.0,43.0
5,2000-01,Regina,Saskatchewan,74.8,65.2,49.4
6,2000-01,Saint John,New Brunswick,70.6,63.8,49.9
7,2000-01,Saskatoon,Saskatchewan,74.0,64.5,50.5
8,2000-01,St. John's,Newfoundland and Labrador,81.3,74.9,49.3
9,2000-01,Thunder Bay,Ontario,74.8,65.1,48.0
10,2000-01,Toronto,Ontario,73.3,63.5,48.0
11,2000-01,Vancouver,British Columbia,70.3,60.2,50.4
12,2000-01,Victoria,British Columbia,74.9,64.6,49.1
13,2000-01,Whitehorse,Yukon,79.4,73.8,47.4
14,2000-01,Winnipeg,Manitoba,71.1,61.9,50.5
15,2000-01,Yellowknife,Northwest Territories,84.8,77.9,47.7
16,2000-02,Charlottetown,Prince Edward Island,67.5,63.3,42.3
17,2000-02,Halifax,Nova Scotia,76.7,70.8,60.5
18,2000-02,Montréal,Quebec,80.6,73.8,59.1
19,2000-02,Ottawa,Ontario,74.8,64.7,55.9
20,2000-02,Québec City,Quebec,76.5,69.4,57.9
21,2000-02,Regina,Saskatchewan,75.9,66.3,49.9
22,2000-02,Saint John,New Brunswick,75.4,68.6,63.0
23,2000-02,Saskatoon,Saskatchewan,76.4,66.9,50.8
24,2000-02,St. John's,Newfoundland and Labrador,83.1,76.5,58.0

Convert the date column to datetime format and Feature engineer the year column

In [11]:
df_pivot['date'] = pd.to_datetime(df_pivot['date'], format="%Y-%m")
df_pivot['Year'] =df_pivot['date'].dt.year
df_pivot.head()

,date,city,province,gasoline_premium,gasoline_regular,natural gas,Year
0,2000-01-01,Charlottetown,Prince Edward Island,67.4,63.3,42.3,2000
1,2000-01-01,Halifax,Nova Scotia,74.9,69.6,49.0,2000
2,2000-01-01,Montréal,Quebec,76.1,68.8,43.0,2000
3,2000-01-01,Ottawa,Ontario,72.9,62.7,47.7,2000
4,2000-01-01,Québec City,Quebec,71.2,64.0,43.0,2000

Feature engineer the month column

In [12]:
df_pivot['month'] = df_pivot['date'].dt.month
df_pivot['month_name'] = df_pivot['date'].dt.month_name()
df_pivot.head()

,date,city,province,gasoline_premium,gasoline_regular,natural gas,Year,month,month_name
0,2000-01-01,Charlottetown,Prince Edward Island,67.4,63.3,42.3,2000,1,January
1,2000-01-01,Halifax,Nova Scotia,74.9,69.6,49.0,2000,1,January
2,2000-01-01,Montréal,Quebec,76.1,68.8,43.0,2000,1,January
3,2000-01-01,Ottawa,Ontario,72.9,62.7,47.7,2000,1,January
4,2000-01-01,Québec City,Quebec,71.2,64.0,43.0,2000,1,January

Feature engineer the seasonal patterns column

In [13]:
df_pivot['season'] = df_pivot['month'].map({
    12: 'Winter', 1: 'Winter', 2: 'Winter',
    3: 'Spring', 4: 'Spring', 5: 'Spring',
    6: 'Summer', 7: 'Summer', 8: 'Summer',
    9: 'Fall', 10: 'Fall', 11: 'Fall'
})
df_pivot.tail()

,date,city,province,gasoline_premium,gasoline_regular,natural gas,Year,month,month_name,season
4427,2023-01-01,Vancouver,British Columbia,203.4,179.3,181.8,2023,1,January,Winter
4428,2023-01-01,Victoria,British Columbia,195.2,173.4,206.0,2023,1,January,Winter
4429,2023-01-01,Whitehorse,Yukon,180.1,169.6,204.8,2023,1,January,Winter
4430,2023-01-01,Winnipeg,Manitoba,170.3,147.2,172.7,2023,1,January,Winter
4431,2023-01-01,Yellowknife,Northwest Territories,173.5,158.0,175.1,2023,1,January,Winter

Feature engineer the difference between the prices of regular gasoline and natural gas

In [14]:

df_pivot['regular_natgas_diff'] = df_pivot['gasoline_regular'] - df_pivot['natural gas']

Feature engineer the difference between the prices of premium gasoline and natural gas

In [15]:
df_pivot['premium_natgas_diff'] = df_pivot['gasoline_premium'] - df_pivot['natural gas']
df_pivot.head()

,date,city,province,gasoline_premium,gasoline_regular,natural gas,Year,month,month_name,season,regular_natgas_diff,premium_natgas_diff
0,2000-01-01,Charlottetown,Prince Edward Island,67.4,63.3,42.3,2000,1,January,Winter,21.0,25.1
1,2000-01-01,Halifax,Nova Scotia,74.9,69.6,49.0,2000,1,January,Winter,20.6,25.9
2,2000-01-01,Montréal,Quebec,76.1,68.8,43.0,2000,1,January,Winter,25.8,33.1
3,2000-01-01,Ottawa,Ontario,72.9,62.7,47.7,2000,1,January,Winter,15.0,25.2
4,2000-01-01,Québec City,Quebec,71.2,64.0,43.0,2000,1,January,Winter,21.0,28.2

Sort the values by city date and province
 and  
 Calculate the monthly change in price of gasoline and natural gas

In [16]:
df_pivot = df_pivot.sort_values(['city', 'province', 'date'])
df_pivot['regular_monthly_change'] = df_pivot.groupby(['city', 'province'])['gasoline_regular'].diff()
df_pivot['premium_monthly_change'] = df_pivot.groupby(['city', 'province'])['gasoline_premium'].diff()
df_pivot['natgas_monthly_change'] = df_pivot.groupby(['city', 'province'])['natural gas'].diff()
df_pivot.tail()

,date,city,province,gasoline_premium,gasoline_regular,natural gas,Year,month,month_name,season,regular_natgas_diff,premium_natgas_diff,regular_monthly_change,premium_monthly_change,natgas_monthly_change
4367,2022-09-01,Yellowknife,Northwest Territories,189.4,173.9,185.0,2022,9,September,Fall,-11.1,4.4,-3.2,-3.2,8.4
4383,2022-10-01,Yellowknife,Northwest Territories,195.7,180.2,174.2,2022,10,October,Fall,6.0,21.5,6.3,6.3,-10.8
4399,2022-11-01,Yellowknife,Northwest Territories,189.6,174.1,189.5,2022,11,November,Fall,-15.4,0.1,-6.1,-6.1,15.3
4415,2022-12-01,Yellowknife,Northwest Territories,174.2,158.7,179.1,2022,12,December,Winter,-20.4,-4.9,-15.4,-15.4,-10.4
4431,2023-01-01,Yellowknife,Northwest Territories,173.5,158.0,175.1,2023,1,January,Winter,-17.1,-1.6,-0.7,-0.7,-4.0

In [17]:
df_pivot.isnull().any()

date                      False
city                      False
province                  False
gasoline_premium          False
gasoline_regular          False
natural gas               False
Year                      False
month                     False
month_name                False
season                    False
regular_natgas_diff       False
premium_natgas_diff       False
regular_monthly_change     True
premium_monthly_change     True
natgas_monthly_change      True
dtype: bool

In [ ]:
df_pivot.to_csv("pivot_data.csv", index=False)
from google.colab import files
files.download("pivot_data.csv")